import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';

// Precache the files generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache API responses
registerRoute(
    ({ request }) => request.destination === 'document',
    new NetworkFirst({
        cacheName: 'pages-cache',
    })
);
